# -*- coding: utf-8 -*-
"""Aula 1 - Primeiros passos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16x5uFc5pbiaWYHhqSeVNCnWy0Eu0Llec
"""

print("Hello world!")

print("Olá, Maria!")
print("Sua idade é 23 anos.")
print("Seu peso é 52kg.")

nome = "Maria"
idade = "23"
peso = "52"
print("Olá, "+nome+" !")
print("Sua idade é "+idade+" anos.")
print("Seu peso é "+peso+" kg")

print(f"Olá, {nome}!")
print(f"Sua idade é {idade} anos.")
print(f"Seu peso é {peso} kg.")